export const LOAD_CHARACTER_REQUEST = 'LOAD_CHARACTER_REQUEST';
export const LOAD_CHARACTER_SUCCESS = 'LOAD_CHARACTER_SUCCESS';
export const LOAD_CHARACTER_FAILURE = 'LOAD_CHARACTER_FAILURE';
export const LOAD_CHARACTER_MATCHES_REQUEST = 'LOAD_CHARACTER_MATCHES_REQUEST';
export const LOAD_CHARACTER_MATCHES_SUCCESS = 'LOAD_CHARACTER_MATCHES_SUCCESS';
export const LOAD_CHARACTER_MATCHES_FAILURE = 'LOAD_CHARACTER_MATCHES_FAILURE';
export const LOAD_CHARACTER_MATCHUP_REQUEST = 'LOAD_CHARACTER_MATCHUP_REQUEST';
export const LOAD_CHARACTER_MATCHUP_SUCCESS = 'LOAD_CHARACTER_MATCHUP_SUCCESS';
export const LOAD_CHARACTER_MATCHUP_FAILURE = 'LOAD_CHARACTER_MATCHUP_FAILURE';
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const ADD_MATCH = 'ADD_MATCH';